### PR TITLE
FS-4086-view-entire-application

### PR DESCRIPTION
**Pull request by ramsharma-prog**
### Ticket
https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?selectedIssue=FS-4086

### Description
Lead assessor and assessor can view the entire application 

### Screenshots of UI changes

Screenshot 2024-04-23 at 16 55 30

Screenshot 2024-04-22 at 18 18 22

Screenshot 2024-04-22 at 18 18 32

### CODE REVIEW

**Comment by rayhan15243** [comment]
Tested locally with @ramsharma-prog, works as expected for Assessors and Lead Assessors. Commenters can't get access as expected. 

CC: @tejvath

**Review by hamzabinkhalid — APPROVED** [review]
LGTM

**Review by adamdavies1 — DISMISSED** [review]
LGTM

**Review by adamdavies1 — DISMISSED** [review]
lgtm

**Review by adamdavies1 — DISMISSED** [review]
LGTM

**Review by rayhan15243 — APPROVED** [review]

**Pull request merged**
